### ISSUE TITLE
Chat and notes for 20.04 beta version.

### ISSUE THREAD

**Issue by RattyDAVE** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#10]
20.04 is the new long term release to replace 18.04. This will released in April 2020.

There is an alpha ubuntu build and I have rebased the 18.04 to 20.04 and added the startup scrip script from later versions.
Note: packages are prebuilt using the ubuntu repo not from source.

So we should have the start of a really good version!

**Comment by RattyDAVE** [comment]
20.04 has some serious docker container issues. And wont build due to lots of package issues. It is set on autobuild so when ubuntu 20.04 update it will retry automatically.

**Comment by knvish** [comment]
After running docker image, please advise how do I coneect to the container via GUI?

**Comment by RattyDAVE** [comment]
What part of the instructions are you stuck on?

https://github.com/RattyDAVE/docker-ubuntu-xrdp-mate-custom

if on a windows machine use rdp then put in the docker host IP address.

**Comment by RattyDAVE** [comment]
For example on a linux machine....

![image](https://user-images.githubusercontent.com/9049822/78294780-d6b8e200-7522-11ea-8333-293a07970d1b.png)

**Comment by RattyDAVE** [comment]
If on windows run ....

```
mstsc
```

Then put in the ip address of the docker host.

**Comment by knvish** [comment]
Thanks for your response, I am stuck at finding out the IP address of my
windows 10, on which I am running Docker for Windows and trying out your
image.
Thanks & Regards
Vish
Tel: +91 8296484957
_________________________________
Keep calm and carry on

**Comment by RattyDAVE** [comment]
If you are running on the same machine then you can use `localhost` or `127.0.0.1`

**Comment by knvish** [comment]
This option didn't work for me. Setup is laptop running Windows 10, Docker
for Windows and your image instance running.
How many IP addresses do you have? One for Windows box, another for Docker
running a Linux kernel and the container. I am unable find the IP address
for these devices.

**Comment by RattyDAVE** [comment]
The port on the command line -p 3389:3389 forwards the port from the host ip to the docker container. 

As a test run the following

```
docker run -p 13389:3389 -dit rattydave/docker-ubuntu-xrdp-mate-custom:19.10
```

NOTE the port forward is changed to 13389

Then to access

```
mstsc /v:127.0.0.1:13389
```

You SHOULD get a connection and a login window.

**Comment by knvish** [comment]
Thanks, I got the login window now. But if I login as User and pass, login
fails for display 0.

Please advise

**Comment by RattyDAVE** [comment]
on that test there are no users created...

Please follow the the intructions on the main page

https://hub.docker.com/repository/docker/rattydave/docker-ubuntu-xrdp-mate-custom

I would suggest somthing like this.

```
echo "user:pass:N" > CREATEUSERS.TXT
docker run --name RattyDAVE19.10 \
           --privileged=true \
           -p 13389:3389 \
           -v CREATEUSERS.TXT:/root/createusers.txt \
           -dit --restart unless-stopped \
           rattydave/docker-ubuntu-xrdp-mate-custom:19.10
```

**Comment by knvish** [comment]
Thanks, how do I write these long instructions in Windows command line
terminal?
Multiple instructions in a single cmd terminal? Sorry for the trouble.

**Comment by RattyDAVE** [comment]
Windows is not my area.

Try
```
echo "user:pass:N" > CREATEUSERS.TXT
```

Then 

```
docker run --name RattyDAVE19.10 --privileged=true -p 13389:3389 -v CREATEUSERS.TXT:/root/createusers.txt -dit --restart unless-stopped rattydave/docker-ubuntu-xrdp-mate-custom:19.10
```

**Comment by RattyDAVE** [comment]
As this is not an issure with the container. I am closing this.

btw 20.04 should be out soon!

**Comment by knvish** [comment]
Thanks for your email

**Comment by knvish** [comment]
Yes, I installed 20.04 but the update section stalls at software cache
refresh stage and does not close.

**Comment by Gymnae** [comment]
I just installed :latest, which is stated to be 20.04 - It appears that sound is not working, I tried with guacamole and remmina, both do not get audio forwarded. pluseaudio refuses to start:
```
$ pulseaudio 
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
```

Alsa also appears to not play well: 

```
$ alsamixer 
cannot open mixer: No such file or directory

```
