### ISSUE TITLE
Clipboard not working with Ubuntu 19.10

### ISSUE THREAD

**Issue by fflo** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#11]
Amazing work. Thank you!

Do you have a hint why the clipboard (copy / paste) is not working using Ubuntu 19.10 (latest) image?

**Comment by RattyDAVE** [comment]
I do! Not going to be much help at the moment.

The 18.04 is the best version at the moment. 19.10 was looking promising but I think the Ubuntu developers changed their focus. (The packages are not as tighly controlled in the non LTS versions.)

I am going to revisit this for the 20.04 LTS version. (and that will be the next stable).

You may see some progress on this end of Feb.

Regards!

**Comment by fflo** [comment]
Clipboard (copy / paste) is also not working using Ubuntu 18.04 (stable). Does it work for you?

**Comment by fflo** [comment]
finally succeeded debugging why it's not working:
`/usr/local/sbin/xrdp-chansrv: error while loading shared libraries: libfdk-aac.so.1: cannot open shared object file: No such file or directory`

Seems that auto-remove deinstall libfdk-aac1 which is needed by xrdp-chansrv. Without this library xrdp-chansrv becomes stale:
` 1736 ?        Z      0:00 [xrdp-chansrv] <defunct>`

Manually installing it into the docker container does fix the issue:
`apt update && apt install libfdk-aac1`

**Comment by fflo** [comment]
`--- Dockerfile.orig	2019-12-22 23:11:25.000000000 +0100
+++ Dockerfile	2019-12-23 10:49:00.000000000 +0100
@@ -46,7 +46,7 @@
         curl \
         wget \
         epiphany-browser && \
-    ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime && dpkg-reconfigure -f noninteractive tzdata && \
+    ln -fs /usr/share/zoneinfo/UTC /etc/localtime && dpkg-reconfigure -f noninteractive tzdata && \
     apt-get -y install \
         git \
         libxfont-dev \
@@ -81,13 +81,15 @@
     git clone https://github.com/neutrinolabs/pulseaudio-module-xrdp.git && cd pulseaudio-module-xrdp && ./bootstrap && ./configure PULSE_DIR="/tmp/pulseaudio-$pulsever" && make && \
     cd /tmp/pulseaudio-$pulsever/pulseaudio-module-xrdp/src/.libs && install -t "/var/lib/xrdp-pulseaudio-installer" -D -m 644 *.so && \
     cd /root && \
-    git clone -b devel https://github.com/neutrinolabs/xrdp.git && \
-    git clone -b devel https://github.com/neutrinolabs/xorgxrdp.git && \
+    git clone -b master https://github.com/neutrinolabs/xrdp.git && \
+    git clone -b master https://github.com/neutrinolabs/xorgxrdp.git && \
     cd /root/xrdp && ./bootstrap && ./configure --enable-fuse --enable-jpeg --enable-vsock --enable-fdkaac --enable-opus --enable-mp3lame --enable-pixman && make && make install && \
     cd /root/xorgxrdp  && ./bootstrap && ./configure && make && make install && \
     cd /root && \
     rm -R /root/xrdp && \
     rm -R /root/xorgxrdp && \
+    # bugfix clipboard bug: [xrdp-chansrv] <defunct>
+    apt-mark manual libfdk-aac1 && \
     apt-get -y purge \
         git \
         libxfont-dev \
@@ -122,7 +124,7 @@
     sed -i '/TerminalServerAdmins/d' /etc/xrdp/sesman.ini  && \
     sed -i -e '/DisconnectedTimeLimit=/ s/=.*/=0/' /etc/xrdp/sesman.ini && \
     sed -i -e '/IdleTimeLimit=/ s/=.*/=0/' /etc/xrdp/sesman.ini && \
-    xrdp-keygen xrdp auto  && \
+    #xrdp-keygen xrdp auto  && \ # hint: moved to autostartup.sh for security
     mkdir -p /var/run/xrdp && \
     chmod 2775 /var/run/xrdp  && \
     mkdir -p /var/run/xrdp/sockdir && \`

**Comment by RattyDAVE** [comment]
Thank you....I am travelling at the moment... will look at the pull when I can.. Thanks again!On 23 Dec 2019 09:58, fflo <notifications@github.com> wrote:finally succeeded debugging why it's not working:
/usr/local/sbin/xrdp-chansrv: error while loading shared libraries: libfdk-aac.so.1: cannot open shared object file: No such file or directory
Seems that auto-remove deinstall libfdk-aac1 which is needed by xrdp-chansrv. Without this library xrdp-chansrv becomes stale:
 1736 ?        Z      0:00 [xrdp-chansrv] <defunct>
Manually installing it into the docker container does fix the issue:
apt update && apt install libfdk-aac1

**Comment by fflo** [comment]
You're welcome.

For the sake of security I also have moved xrdp-keygen to `autostartup.sh` to avoid static private keys within the docker image.
```
#!/bin/bash

# setup Timezone
if [[ -z "${TZ}" ]]; then
   ln -fs /usr/share/zoneinfo/UTC /etc/localtime
   dpkg-reconfigure -f noninteractive tzdata
else
   ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime
   dpkg-reconfigure -f noninteractive tzdata
fi

# generate
if [ ! -f /etc/xrdp/rsakeys.ini ]
  then
    xrdp-keygen xrdp auto
fi
...
````
Happy Xmas.

**Comment by RattyDAVE** [comment]
Thank you I have pushed and built...

**Comment by RattyDAVE** [comment]
Have you pulled the latester version and tested?

**Comment by fflo** [comment]
Yes, using `rattydave/docker-ubuntu-xrdp-mate-custom:latest` or `rattydave/docker-ubuntu-xrdp-mate-custom:19.10` the issue is fixed, now. Thank you!

Is there a reason why you have chosen to setup `xrdp.ini` `new_cursors=false`. The mouse pointer looks much better using high resolution with `new_cursors=true`.

**Comment by RattyDAVE** [comment]
This is a cary over from a previous issue where the cursor was not displaying correctly. 

I have not revisited this since.

Ill will make that change and have test.

Thasnk you.
