### ISSUE TITLE
Clipboard File Transfer Only One Direction

### ISSUE THREAD

**Issue by Sheathan** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#12]
The clipboard only seems to be working one way when it comes to files. Text can be copy and pasted from both directions (client to server and server to client) without any issues. Files can be copy/pasted from the server (linux container) to the client (Windows 8/10 in my case), but not from the client to the server. I have compiled xrdp from source on a full VM and still seem to encounter the same behavior. Is there a configuration inside of the docker container that may be changed or is this a limitation of xrdp in general?

**Comment by RattyDAVE** [comment]
I am not too sure what the issue you describe is. Can you attach screen shots?

https://github.com/neutrinolabs/xrdp/issues/220

If it is that it looks like a fuse issue that i think I can fix.

**Comment by Sheathan** [comment]
Fuse is enabled on your container and working fine (as far as I can tell). I even compiled xrdp myself with fuse enabled to double check, and it's the same issue.

I will try to take a video to better explain what I mean, there is no error, there is nothing to screenshot.

If I am on the container, I have a file called notes.txt on the desktop. I can right click and copy this file, and then go into my Windows and paste this file onto my own desktop, which is normal for an RDP session. However, if I have a file on my Windows desktop and I right click to copy, when I try to paste the file into the Linux desktop, the paste button is greyed out - it's as if nothing has been copied to the clipboard. So this only works in one direction, copying files from Linux to Windows, but not Windows to Linux.

**Comment by Sheathan** [comment]
Here's a quick demo of what I'm trying to describe.

![2020-05-11-12-21-03](https://user-images.githubusercontent.com/13694963/81585413-2096b280-9382-11ea-8beb-5b2d2c3c01b1.gif)

**Comment by RattyDAVE** [comment]
What tag are you using? 20.04?

This is an intresting problem. I dont have a windows machine to hand to test. I need to get one setup.

I have also looked at the other "fixes" and it seems everything is corect in the build process. 

When I origionally did the 20.04 version it seems that there was big changes from 19.04 and 19.10 to 20.04 and needed a few changes to get working.

So looking at the forums and seeing issues since April 2020 there is nothing i can find. So either we are the 1st or no one else has reported issues.

As of time of posting I have rebuilt the 20.04 tag with the latest version of xrdp.

Hope this helps.

**Comment by Sheathan** [comment]
I was using the latest, which at the time was pointing to your 20.04 image. I have been using your container for about a month and this issue was also present in the 19.x images. I just pulled the 20.04 image again and spun it up, with the same results. I am really suspecting this may be an issue with xrdp rather than anything in your configuration or container, but I can't be 100% sure as I don't know where to look for this kind of thing.

Am I the only person actually using Windows to RDP to a linux machine? I don't know why else this container or xrdp would exist haha.

Also on a side note, which I now suspect is a result of not having a Windows box to test with, it would be a lot better to use NLA (Network Level Authentication) with xrdp. That's what causes this notification when connecting. When I compiled xrdp myself, I found that by default it's using NLA, but your container is not.

![image](https://user-images.githubusercontent.com/13694963/81702629-898d3180-9439-11ea-85d7-3b03cac57720.png)

I can open a separate issue if this is something you may plan on changing, otherwise that's fine too.

**Comment by RattyDAVE** [comment]
I have spent quite a bit of time with this and I think the xrdp copy issue is one we are going to have to live with for now. 

As for NLA that was a chice a made as xfreerdp and remmina do not work well with NLA. 
If you want this is an easy change in the xrdp.ini file.

**Comment by Sheathan** [comment]
I appreciate you taking the time to take a look! I'll try raising the issue on xrdp git and see if anybody has encountered it either, I think it's a problem on their side.

I did change it the ini file, I wasn't sure if you didn't know about it or did it on purpose, which you did, so that's all good :)

Thanks for everything!

**Comment by RattyDAVE** [comment]
Not a problem. It is aways good to get some feedback and another perspective.

Also your use case is very different from mine so will encounter diffent problems.

**Comment by hifihedgehog** [comment]
@RattyDAVE, why exactly can't we copy into Linux?

**Comment by RattyDAVE** [comment]
The version of xrdp and xorg in the 20.04 repository does not have the compile options set.
