### ISSUE TITLE
Support for KDE instead of Mate

### ISSUE THREAD

**Issue by Malzmeier** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#13]
Is it possible to change the desktop from Mate to KDE?

I tried by myself by replacing mate packages with kubuntu-desktop in Dockerfile, but when trying to connect via rdp it seems to not starting the KDE Plasma desktop.

I didn’t figure out what’s the problem.

**Comment by RattyDAVE** [comment]
KDE requires lots of hooks, dependencies and services. Also it would make this already huge container much larger.

Did you change the .Xsession file to point to KDE?

It might be worth looking at https://github.com/KDE/docker-neon

DAVE

**Comment by Malzmeier** [comment]
Ok, it‘s just that i’m using Kubuntu on my desktop and thought it would be great to have it on docker.
I customised your docker image to my needs with all the applications I need, so it’s working fine for me :-)

On my tries I changed the .Xsession file.
I’ll take a look at the docker-neon, maybe I can fix my error on KDE.

Thanks for your support
