### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by rickey77220** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#14]
Hi i can't connect to session. I don't understand what's happening.
Thank you for your help !

docker creation:
![image](https://user-images.githubusercontent.com/8083474/89528117-c96e7580-d7ea-11ea-8c39-7b6f48b333f5.png)

docker log:
![image](https://user-images.githubusercontent.com/8083474/89528144-d4290a80-d7ea-11ea-908d-20ae66be9822.png)

session error:
![image](https://user-images.githubusercontent.com/8083474/89528160-ddb27280-d7ea-11ea-9b1a-04d53d4163c3.png)

docker log:
![image](https://user-images.githubusercontent.com/8083474/89528274-0cc8e400-d7eb-11ea-85e7-e635962b1d9f.png)

**Comment by hirenapatel1109** [comment]
I have the same issue.

**Comment by RattyDAVE** [comment]
I am investigating.

**Comment by RattyDAVE** [comment]
Can you try the full path in the createusers.txt mapping.

From what you you provided it look all correct. I have just tried this on on a fresh pull.

```
mkdir -p /share/media/docker/configs/rattydave
mkdir -p  /share/media/docker/configs/rattydave/home
echo user1:pass1:Y >  /share/media/docker/configs/rattydave/createusers.txt
echo user2:pass2:N >> /share/media/docker/configs/rattydave/createusers.txt

docker run --name RattyDAVE \
           -p 3389:3389 \
           -v /share/media/docker/configs/rattydave/createusers.txt:/root/createusers.txt \
           -v /share/media/docker/configs/rattydave/home:/home \
           -d --restart unless-stopped \
           rattydave/docker-ubuntu-xrdp-mate-custom:latest

```
And this works as expected.

**Comment by rickey77220** [comment]
Thank you RattyDave. It seems that user created in createusers.txt are not take in account during autostartup.sh execution.

**Comment by RattyDAVE** [comment]
Cross post.  That points to to what I was looking at too.

**Comment by hirenapatel1109** [comment]
Sorry for the late response. I still run into that error.  Here is what I ran:
`patelhiren@HirenMSI:/mnt/c/users/Public/Documents$ echo user1:pass1:Y > createusers.txt`
`patelhiren@HirenMSI:/mnt/c/users/Public/Documents$ echo user2:pass2:N >> createusers.txt`
`patelhiren@HirenMSI:/mnt/c/users/Public/Documents$ cat createusers.txt
user1:pass1:Y
user2:pass2:N`

`patelhiren@HirenMSI:/mnt/c/users/Public/Documents$ docker run --name RattyDAVE -p 3389:3389 -v /mnt/c/users/Public/Documents/createusers.txt:/root/createusers.txt -d --restart unless-stopped rattydave/docker-ubuntu-xrdp-mate-custom:latest`

Both user1:pass1:Y and user2:pass2:N give me the following error:
![image](https://user-images.githubusercontent.com/44535821/91001148-90772480-e590-11ea-81e2-cf672b271177.png)
![image](https://user-images.githubusercontent.com/44535821/91001171-9c62e680-e590-11ea-9d2a-03a824e6bb21.png)

Any suggestions?

**Comment by RattyDAVE** [comment]
It looks like a permission problem in /mnt/c/users/Public/Documents

When you run the following....... 

patelhiren@HirenMSI:/mnt/c/users/Public/Documents$ echo user1:pass1:Y > createusers.txt
patelhiren@HirenMSI:/mnt/c/users/Public/Documents$ echo user2:pass2:N >> createusers.txt
patelhiren@HirenMSI:/mnt/c/users/Public/Documents$ cat createusers.txt

No createusers.txt is created.

**Comment by hirenapatel1109** [comment]
I believe that was just a copy-paste error. Here is a screenshot of what it looks like:
![image](https://user-images.githubusercontent.com/44535821/91089414-26569200-e619-11ea-8caa-6bd9db48ec0d.png)

The file was created successfully.

**Comment by RattyDAVE** [comment]
It is working fine here. What user is docker running as? Does it have access to /mnt/c/users/Public/Documents ?
It is looking like a permission problem to me.

I would do...

```
echo user1:pass1:Y > /tmp/createusers.txt
echo user2:pass2:Y >> /tmp/createusers.txt

docker run --name RattyDAVE -p 3389:3389 -v /tmp/createuser.txt:/root/createusers.txt -d --restart unless-stopped rattydave/docker-ubuntu-xrdp-mate-custom:latest
```

**Comment by hirenapatel1109** [comment]
I tried that and I still get the same error. I SSHed into that container and createusers.txt is an empty directory for me, not a text file.

`root@35f539ffa9d8:/# cat root/createusers.txt/`
`cat: root/createusers.txt/: Is a directory`

This probably suggests the file does not get copied correctly. I am on Windows and am using WSL. 

I verified that the file in my WSL /tmp/createusers.txt was a text file with the correct information:
`$ cat tmp/createusers.txt`
`user1:pass1:Y`
`user2:pass2:Y`

Is there a workaround for this? Or maybe creating a default user like ubuntu:ubuntu would be nice if the system can't find a valid createusers.txt file.

**Comment by hirenapatel1109** [comment]
I found a workaround for this:

I started the container without a createusers.txt volume mount.
`docker run --name RattyDAVE -p 3389:3389 -d --restart unless-stopped rattydave/docker-ubuntu-xrdp-mate-custom:latest`
I then SSHed into the container and created the /root/createusers.txt file with the credentials.
I then `chmod +x autostartup.sh` and `./autostartup.sh`

Seems to be working.

**Comment by RattyDAVE** [comment]
Creating a default user is asking for trouble security wise. RDP is not a secure protocol anyway. But having a default user will break all the security standards.

As for the issue you are having it looking to be the strange implementation of how you have docker installed.

**Comment by recklessop** [comment]
I have the same issue ... standard docker install. Ill dig into it more and see if i can figure it out

**Comment by recklessop** [comment]
I just created a pull request that I think will fix the issue. https://github.com/RattyDAVE/docker-ubuntu-xrdp-mate-custom/pull/16

**Comment by luwanglin** [comment]
> I found a workaround for this:
> 
> I started the container without a createusers.txt volume mount.
> `docker run --name RattyDAVE -p 3389:3389 -d --restart unless-stopped rattydave/docker-ubuntu-xrdp-mate-custom:latest`
> I then SSHed into the container and created the /root/createusers.txt file with the credentials.
> I then `chmod +x /root/autostartup.sh` and `./root/autostartup.sh`
> 
> Seems to be working.

Thank you, your method does work

**Comment by eino-makitalo** [comment]
I found one problem ...
I created createusers.txt file and used COPY -command in dockerfile to create user like...

`user:user:Y`

It seems that login fails because system creates /home/user with root owned...
I fixed it by command  ` chown user:user   /home/user`    and login works

**Comment by RattyDAVE** [comment]
Just to to be clear and aid your debugging.

Run the following.

```
echo "user:pass:N" > CREATEUSERS.TXT
docker run --name RattyDAVE20.04 \
           --privileged=true \
           -p 3389:3389 \
           -e TZ="Europe/London" \
           -v ${PWD}/CREATEUSERS.TXT:/root/createusers.txt \
           -dit --restart unless-stopped \
           rattydave/docker-ubuntu-xrdp-mate-custom:20.04
```
Then inside the container, looking at the permissions

![image](https://user-images.githubusercontent.com/9049822/102977989-b17a6280-44fb-11eb-8cf2-aa72369c6ae4.png)

I can all login using

```
xfreerdp /v:127.0.0.1
```

with the username `user` and password `pass`

Hope this helps.
