### ISSUE TITLE
Home directory is created with wrong permission

### ISSUE THREAD

**Issue by eino-makitalo** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#17]
It seems that system is creating  /home/user  with root owned  but it should be owned by user itself.

**Comment by RattyDAVE** [comment]
I have checked using the internal file system and this works as expected.

I have seen this problem on external file systems (outside the docker container) so this is not an issue with this container but the host system configuration.

**Comment by RattyDAVE** [comment]
Just to to be clear and aid your debugging.

Run the following.

```
echo "user:pass:N" > CREATEUSERS.TXT
docker run --name RattyDAVE20.04 \
           --privileged=true \
           -p 3389:3389 \
           -e TZ="Europe/London" \
           -v ${PWD}/CREATEUSERS.TXT:/root/createusers.txt \
           -dit --restart unless-stopped \
           rattydave/docker-ubuntu-xrdp-mate-custom:20.04
```
Then inside the container, looking at the permissions

![image](https://user-images.githubusercontent.com/9049822/102977989-b17a6280-44fb-11eb-8cf2-aa72369c6ae4.png)

I can all login using

```
xfreerdp /v:127.0.0.1
```

with the username `user` and password `pass`

Hope this helps.

**Comment by eino-makitalo** [comment]
I found. It was my fault. In my dockerfile  I used command  `WORKDIR /home/user`  
and because I did not switch user away from root it overrides permissions...

You can close this, sorry.

**Comment by RattyDAVE** [comment]
No problem. Happy to help.
