### ISSUE TITLE
No root access for the user

### ISSUE THREAD

**Issue by telegrambotdev** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#19]
```
echo "test:test:N" > CREATEUSERS.TXT
docker run --name RattyDAVE20.04 \
           --privileged=true \
           -p 3389:3389 \
           -e TZ="Europe/London" \
           -v ${PWD}/CREATEUSERS.TXT:/root/createusers.txt \
           -dit --restart unless-stopped \
           rattydave/docker-ubuntu-xrdp-mate-custom:20.04
```

I ran this.

But after  login in to rdp,I don't have sudo access.getting the below error,kindly give me an urgent work around @RattyDAVE 

`getting "test not is not in the sudoers file.  This incident will be reported" `

**Comment by RattyDAVE** [comment]
what is in the contents of the ${PWD}/CREATEUSERS.TXT file?

**Comment by RattyDAVE** [comment]
That does not have sudo access... 

In the instructions.....

This file contains 3 fields (username:password:is_sudo). Where username is the login id. Password is the password. is_sudo does the user have sudo access(only Y is recognised). It also needs a "newline" at the end of the line.

Example of a CREATEUSERS.TXT file

mickey:mouse:N
daisy:duke:Y
dog:flash:n
morty:rick:wubba
In this example 4 users will be created and only daisy will have sudo rights. At every reboot it will check this file and ADD any new users.

So in YOUR file...

echo "test:test:Y" > CREATEUSERS.TXT

**Comment by telegrambotdev** [comment]
let me check and report back right now

**Comment by telegrambotdev** [comment]
> That does not have sudo access...
> 
> In the instructions.....
> 
> This file contains 3 fields (username:password:is_sudo). Where username is the login id. Password is the password. is_sudo does the user have sudo access(only Y is recognised). It also needs a "newline" at the end of the line.
> 
> Example of a CREATEUSERS.TXT file
> 
> mickeyN
> daisy:duke:Y
> dog:flash:n
> morty:rick:wubba
> In this example 4 users will be created and only daisy will have sudo rights. At every reboot it will check this file and ADD any new users.
> 
> So in YOUR file...
> 
> echo "test:test:Y" > CREATEUSERS.TXT

Worked. Thank you
