### ISSUE TITLE
Automatically start a graphical application

### ISSUE THREAD

**Issue by Cyanat** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#21]
Hi!
First, thanks for this very useful container.

Here is my problem: I would like to use this virtual desktop to give access from outside using application such as Teamviewer or Anydesk. So these applications need to be started right after the startup of this container.
I've tried to add this command in my startup.sh:
`DISPLAY=:10.0 su - myuser -c "Anydesk&"`
It fails, because this is a graphical application, and so need to be runned while a xrdp session is on, which is not the case on the startup.
What would be the solution? Is there anyway to autmatically start a RDP session?

Thanks.

**Comment by RattyDAVE** [comment]
Hi,

I am unsure what you are trying achieve. Or what the end goal is.

You can already screen share using VNC in this container. 

I suspect this is not what you are after and you want some sort of auto login and start.

The following may help.

The order of where applications can start is....

1) Startup.sh
	This runs as soon as the docker container is started.
2) Services using supervisord
	In /etc/supervisor/conf.d the services scripts are executed.
3) Window manager
	Once signed in then the window manager autostart in the standard way.

**Comment by Cyanat** [comment]
Hi,
Thanks for your response.
Anydesk and Teamviewer are tools allowing to access the server from internet without configuring any port translation (which is not the case with VNC or XRDP). I would like to propose this solution for my user who are not able to setup a port translation.

Currently, I'm obliged to start a xrdp session and manually start one of these applications. And after each reboot, or if I close the session, I have to do this process again. I would like to have my anydesk or teamviewer access up right after the boot.

Of course:
- This container automatically start on boot
- I have noticed the use of startup.sh, but during its execution, there is no xrdp session so I can't start Anydesk and redirect it to DISPLAY=:10.0
