### ISSUE TITLE
sound support

### ISSUE THREAD

**Issue by alturismo** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#5]
hi, just wanted to ask if its possible to add sound support to the docker,
i have added a usb sound card and added it to devices, but looks like the kernel driver is not included.

and thanks alot for this nice docker

**Comment by RattyDAVE** [comment]
Sound is something I have been experimenting with.

Below and including Ubuntu 19.04 this needs a huge amount of work to impliment. This then breaks the minimal and easy to modify structure of the Dockerfile. I am aware this is used as a base for quite a few other projects.

Now with that above statement out the way. I have been experimenting with this for quite a while. And it looks 19.10 might be the version. I have noticed that in the repo there are references to the xrdp pulse audio package. Currently it is not there yet.

Where does this leave the sound support? Unknown at present. All the soloutions I have tried currently are unacceptable and cause more issues. I am open to suggestions if anyone has a bright idea.

**Comment by RattyDAVE** [comment]
Intresting... that is much cleaner than I have been doing before. 

You have this working with this on rattydave/docker-ubuntu-xrdp-mate-custom:19.04 ?

I am going to see if i can get into 19.10.

Ill keep this updated.

**Comment by alturismo** [comment]
sadly not, sound settings are there, dummy output too, but no "dummy" hardware or no usb hardware,
my guess, no sound modules loaded in kernel ... lets see what 19.10 comes up with

**Comment by RattyDAVE** [comment]
I have made a start on the sound intergration. in 19.10.

Pulseaudio is install 
xrdp pulseaudo modules are installed too.

**Comment by alturismo** [comment]
would be very nice if you get this to work ... ;)

**Comment by RattyDAVE** [comment]
Pre alpha alpha alpha... shortly

19.10test
