### ISSUE TITLE
xrdp vaapi support

### ISSUE THREAD

**Issue by alturismo** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#6]
may another question, actually no idea if thats even possible, using vaapi for hw acceleration to render xrdp sessions ?

what is working, using gstreamer to get video support in vlc as sample with vaapi, but i couldnt really find anything about hw acceleration in xrdp ...

**Comment by RattyDAVE** [comment]
This is not going to happen. This requires hardware to do the encoding.

**Comment by alturismo** [comment]
ok, thanks for the info, thats why i probably couldnt find anything about it ...
just hoped cause hw acc video inside docker with gstreamer seems to work ;)

just in case interested,
sudo apt install gstreamer1.0-vaapi gstreamer1.0-libav

video playback at least "possible" ;)

**Comment by RattyDAVE** [comment]
I have not done any testing so I may be incorrect.

Points to consider.

How are you running docker on the host machine?

Is X installed or another window manager installed on the docker host 
machine?

Is there a video card or GPU installed on the host machine?

Could be that gstreamer fails back to software?

I run my docker host machine in a minimal environment. (Rancher on bare 
metal). And headless, so no video card.

Do you know of any other docker containers that use vaap? So we can 
compare and test?

**Comment by alturismo** [comment]
well, i run unraid as host, no X installed

im using the igpu (UHD630) for dockers by enabling --device /dev/dri
sample Plex, Emby, TVHeadend, Handbrake ... they use then hw de/encoding by igpu.

but all these are video decoders/encoders only ... so nothing like xrdp ... thats why i asked ;)

if its not implemented by xrdp ... i guess it will be hard then ;) and X through vaapi, no idea here ...

**Comment by RattyDAVE** [comment]
Ah, thats confirmed what I have found too.

It is dependent on hardware.

Then the answer is a NO.

Not going to implement or spend any more time on this.

Sorry about the bad news. I have no problem with anyone building on what 
I have done.

**Comment by alturismo** [comment]
thanks alot for taking a look
