### ISSUE TITLE
timezone and locale support

### ISSUE THREAD

**Issue by alturismo** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#7]
as suggestion, timezone and locale support

locale can be adjusted by generating locale (de_DE....) and then is partly working

timezone ... no chance here, even setting date manually, after a restart we back to UK TZ ;)

**Comment by RattyDAVE** [comment]
How are you setting the timezone?

This is what currently sets the time.
```
ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime
dpkg-reconfigure -f noninteractive tzdata
```

I would guess (needs to be tested) the following might work for you.

```
ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
dpkg-reconfigure -f noninteractive tzdata
```

If that works fine then I will prob add something like -e TZ=Europe/Berlin on the docker run line. 

Let me know how this goes.

**Comment by alturismo** [comment]
perfect ;) also persistent due docker restart, so the -e TZ... would be nice

**Comment by RattyDAVE** [comment]
OK.


That's a quick fix. Ill put something together tomorrow. in the 19.10 tag.

**Comment by alturismo** [comment]
nice, then i ll see ow to update all apps settings from 19.04 to .10 ;)

thanks for the quck fix

**Comment by RattyDAVE** [comment]
New feature is the setup script....

So if you have programs that you installed via apt-get you can include 
there.

**Comment by RattyDAVE** [comment]
One other thing how do you set the keyboard layout from UK? Ill include with the timezone change.

**Comment by RattyDAVE** [comment]
I think it is done. Ready for testing.

```
docker run --name RattyDAVE19.10 \
          --privileged=true \
          -p 3389:3389 \
          -e TZ="Europe/London"
          -e LOCALE="en_GB.UTF-8"
          -v %LOCAL_PATH_TO_CREATEUSERS.TXT_FILE%:/root/createusers.txt \
          -v %LOCAL_PATH_TO_STARTUP.SH_FILE%:/root/createusers.txt \
          -v %LOCAL_PATH_TO_HOME_DIRECTORY%:/home \
          -dit --restart unless-stopped \
          rattydave/docker-ubuntu-xrdp-mate-custom:19.10
```

**Comment by alturismo** [comment]
g morning

feedback

i changed the startup variable here to

-v %LOCAL_PATH_TO_STARTUP.SH_FILE%:/root/startup.sh \

dont know if createusers.txt will work (under the users) ? or just a typo ? ;)

and may add as sample

apt -y .... so the confirmation strings are not killing the docker

simple test, docker is quitting when adding for sample this to startup.sh
apt -y update
apt -y install htop

---log ... here its ending "Processing triggers for man-db (2.8.7-3) ..."
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
strace
The following NEW packages will be installed:
htop
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Need to get 80.4 kB of archives.
After this operation, 225 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu eoan/main amd64 htop amd64 2.2.0-2 [80.4 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 80.4 kB in 0s (598 kB/s)
Selecting previously unselected package htop.
Preparing to unpack .../htop_2.2.0-2_amd64.deb ...
Unpacking htop (2.2.0-2) ...
Setting up htop (2.2.0-2) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.24-1ubuntu1) ...
Processing triggers for mime-support (3.63ubuntu1) ...
Processing triggers for man-db (2.8.7-3) ...

when i remove startup.sh path the docker is starting, i guess, there is already a startup.sh in /root for usercreation .... so this all collides, may i missunderstand ...

renaming to other name like startapp.sh wont work either as its not looking for it in your startup.

and final, timezone and locale are both not set, locale is also not available in de_DE.UTF8 as sample.

docker run here

/docker run -d --name='Ubuntu' --net='bridge' --cpuset-cpus='2,3,8,9' --log-opt max-size='10m' --log-opt max-file='3' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'TZ'='Europe/Berlin' -e 'LOCALE'='de_DE.UTF8' -p '43389:3389/tcp' -v '/mnt/user/appdata/Ubuntu':'/home':'rw' -v '/mnt/user/appdata/Ubuntu/_root/createusers.txt':'/root/createusers.txt':'rw' -v '/mnt':'/Unraid':'rw' -v '/mnt/user/appdata/Ubuntu/_root/startapt.sh':'/root/startapt.sh':'rw' --device='/dev/dri' --device='/dev/bus/usb/003/004' --shm-size 2g 'rattydave/docker-ubuntu-xrdp-mate-custom:19.10'

so, startup.sh, may i missunderstood or may as suggest, other path ?
TZ & LOCALE, no idea ;)

**Comment by RattyDAVE** [comment]
I have just check the version on hub.docker.com and it is an old version. Sorry about that. Also my instructions are incorrect too. Not my best day. 

So its not you it is me.

I will test with your settings. 
-e TZ="Europe/Berlin"
-e LOCALE="de_DE.UTF8"

Sorry!

**Comment by alturismo** [comment]
all good ;) just leave a note, cheers.

**Comment by RattyDAVE** [comment]
Just and update. It wasnt me. Seems hub.docker is giving out the old version. Once it is all updated ill let you know.

**Comment by RattyDAVE** [comment]
UPDATE! hub.docker.com has the right version. 

Tested and found one issue. 

```
echo "apt-get update" > ./startup.sh
echo "apt-get install htop -y" > ./startup.sh

docker pull rattydave/docker-ubuntu-xrdp-mate-custom:19.10
docker run --name RattyDAVE19.10 \
           -p 3389:3389 \
           -v ./createusers.txt:/root/createusers.txt \
           -v ./startup.sh:/root/startup.sh \
           -v ./rattydave/home:/home \
           -e TZ="Europe/Berlin" \
           -e LOCALE="de_DE.UTF8" \
           -d --restart unless-stopped \
           rattydave/docker-ubuntu-xrdp-mate-custom:19.10
```

Results

```
Current default time zone: 'Europe/Berlin'
Local time is now:      Tue Oct  8 11:08:50 CEST 2019.
Universal Time is now:  Tue Oct  8 09:08:50 UTC 2019.
Error: 'de_DE.UTF8' is not a supported language or locale
*** update-locale: Error: invalid locale settings:  LANG=de_DE.UTF8
Username: **REMOVED**
Get:1 http://archive.canonical.com/ubuntu eoan InRelease [10.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu eoan InRelease [255 kB]
Get:3 http://security.ubuntu.com/ubuntu eoan-security InRelease [79.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu eoan-updates InRelease [79.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu eoan-backports InRelease [79.7 kB]
Get:6 http://archive.canonical.com/ubuntu eoan/partner Sources [1354 B]
Get:7 http://archive.canonical.com/ubuntu eoan/partner amd64 Packages [1572 B]
Get:8 http://archive.ubuntu.com/ubuntu eoan/main Sources [1060 kB]
Get:9 http://archive.ubuntu.com/ubuntu eoan/restricted Sources [4924 B]
Get:10 http://archive.ubuntu.com/ubuntu eoan/main amd64 Packages [1277 kB]
Get:11 http://archive.ubuntu.com/ubuntu eoan/restricted amd64 Packages [20.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu eoan/multiverse amd64 Packages [188 kB]
Get:13 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages [11.6 MB]
Fetched 14.7 MB in 3s (4851 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  strace
The following NEW packages will be installed:
  htop
0 upgraded, 1 newly installed, 0 to remove and 15 not upgraded.
Need to get 80.4 kB of archives.
After this operation, 225 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu eoan/main amd64 htop amd64 2.2.0-2 [80.4 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 80.4 kB in 0s (505 kB/s)
Selecting previously unselected package htop.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 105664 files and directories currently installed.)
Preparing to unpack .../htop_2.2.0-2_amd64.deb ...
Unpacking htop (2.2.0-2) ...
Setting up htop (2.2.0-2) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.24-1ubuntu1) ...
Processing triggers for mime-support (3.63ubuntu1) ...
Processing triggers for man-db (2.8.7-3) ...
/usr/lib/python2.7/dist-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2019-10-08 11:09:02,423 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-10-08 11:09:02,425 INFO Included extra file "/etc/supervisor/conf.d/xrdp.conf" during parsing
2019-10-08 11:09:02,449 INFO RPC interface 'supervisor' initialized
2019-10-08 11:09:02,450 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-10-08 11:09:02,450 INFO supervisord started with pid 396
2019-10-08 11:09:03,456 INFO spawned: 'xrdp-sesman' with pid 399
2019-10-08 11:09:03,466 INFO spawned: 'xrdp' with pid 400
2019-10-08 11:09:04,470 INFO success: xrdp-sesman entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-08 11:09:04,470 INFO success: xrdp entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

The error 

```
Error: 'de_DE.UTF8' is not a supported language or locale
*** update-locale: Error: invalid locale settings:  LANG=de_DE.UTF8
```

Looking at locale settings.

Looking good!

**Comment by alturismo** [comment]
confirmed

for locale may add this

locale-gen de_DE.UTF-8

this generates the locale ... then update-locale LANG=de_DE.UTF-8 works here

great and thanks, timezone looking good and startup also ;)

**Comment by RattyDAVE** [comment]
Yeah that works manually for me. I am investigating!

**Comment by alturismo** [comment]
some more tests with some startup script with all my apps, working fine.

locale in progress by you, keyboard layout ... even switching to german its still US here, just as note ...

**Comment by RattyDAVE** [comment]
What do you get with shift 3?Also what client are you using? You may need to set the keyboard in that.On 8 Oct 2019 12:54, alturismo <notifications@github.com> wrote:some more tests with some startup script with all my apps, working fine.
locale in progress by you, keyboard layout ... even switching to german its still US here, just as note ...

**Comment by RattyDAVE** [comment]
There for the aid of debugging there are TWO issues here.

1) Keyboard layout.
This is a simple one you may need to set your client to DE layout. 
```xfreerdp /kbd:0x00000407```

2) Locale not set and start up.
Looking into now. (its odd!)

**Comment by alturismo** [comment]
update, keyboard working, forgot to set generic 105 ... default was 104 ...

so all good here with keyboard

**Comment by RattyDAVE** [comment]
I thought it might be that as the UK keyboard needed the same.

**Comment by alturismo** [comment]
about the locale, i made the entries in the startup.sh and its working ... just as note ;)

> apt-get update
apt-get -y install language-pack-de language-pack-gnome-de
locale-gen de_DE.UTF-8
update-locale LANG=de_DE.UTF-8
apt-get -y install apt-utils
apt-get -y install htop
apt-get -y install gstreamer1.0-vaapi gstreamer1.0-libav
apt-get -y install nano
apt-get -y install gedit
apt-get -y install flameshot
apt-get -y install evolution
apt-get -y install evolution-ews
apt-get -y install libreoffice
apt-get -y install wine
apt-get -y install winetricks
dpkg --add-architecture i386
apt-get update
apt-get -y install wine32
cp -r /home/alturismo/opt/epg123/ /opt/
cp -r /home/alturismo/opt/dreamboxedit/ /opt/
dpkg -i /home/alturismo/Downloads/google-chrome-stable_current_amd64.deb
dpkg -i /home/alturismo/Downloads/discord-0.0.9.deb
apt -y --fix-broken install
apt-get -y install apt-clone
apt-get -y install duplicity
apt -y --fix-broken install
apt -y upgrade

**Comment by RattyDAVE** [comment]
I am thinking that maybe setting the locale via varible my not be the best idea. 

Adding the following to the the startup.sh may be a more flixible soloution.

```
apt-get update
apt-get -y install language-pack-de language-pack-gnome-de
locale-gen de_DE.UTF-8
update-locale LANG=de_DE.UTF-8
```

**Comment by RattyDAVE** [comment]
So at this point we have keyboard and language solved!

So.... I am going to hit the close button...

**Comment by alturismo** [comment]
perfect ;)
