### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by alturismo** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#9]
may a question if you would provide the info how you achieved the dynamic screen resolution change without logging on/off (default behavior).

sample, vm here, xrdp session, i need to log off/on when changing client to get proper resolution change, when using your docker its perfectly working without leaving the session.

for an tipp thanks ahead and sorry to open a issue

**Comment by RattyDAVE** [comment]
This was a key feature for me too. Also with the sharing screens..

Xrandr 

You need to install that and enable at compile  with xrdp, xrdp-session and xorgrdp

**Comment by alturismo** [comment]
i installed xrdp from ubuntu repo, now compile from source i guess with some special flags ... i think i drop that, xrandr is installed, but the feature i like from your dockers is not working, nvm ;)

i wait till the 19.10 docker is working again ;)

**Comment by RattyDAVE** [comment]
Did i break 19.10?

**Comment by RattyDAVE** [comment]
I am not saying i broke 19.10.. but the fixed version is just uploading... lol

**Comment by RattyDAVE** [comment]
Here is the script I use.

```
    apt-get -y install git libxfont-dev xserver-xorg-core libx11-dev libxfixes-dev libssl-dev libpam0g-dev libtool libjpeg-dev flex bison gettext autoconf libxml-parser-perl libfuse-dev xsltproc \
        libxrandr-dev python-libxml2 nasm xserver-xorg-dev fuse build-essential pkg-config libpulse-dev m4 intltool dpkg-dev
    cd /root
    git clone -b devel https://github.com/neutrinolabs/xrdp.git
    git clone -b devel https://github.com/neutrinolabs/xorgxrdp.git
    cd /root/xrdp && ./bootstrap && ./configure --enable-fuse --enable-jpeg && make && make install
    cd /root/xorgxrdp  && ./bootstrap && ./configure && make && make install
    rm -R /root/xrdp
    rm -R /root/xorgxrdp
    apt-get -y purge git libxfont-dev libx11-dev libxfixes-dev libssl-dev libpam0g-dev libtool libjpeg-dev flex  bison gettext autoconf libxml-parser-perl libfuse-dev xsltproc libxrandr-dev python-libxml2 \
        nasm xserver-xorg-dev build-essential pkg-config
```

**Comment by alturismo** [comment]
thanks, i ll try both, the fixed 19.10 docker and the script to install xrdp on vm to see if that works.

thanks alot ;)

**Comment by RattyDAVE** [comment]
19.10 upload...

**Comment by alturismo** [comment]
thanks for fixing docker, check ;)

vm with your script, no luck here

installed like your description, enabled and start systemctl xrdp.service

restart

only scrambled picture or black screen here, nvm, docker is up ;)

**Comment by RattyDAVE** [comment]
Are you getting the login screen? If so the it is prob a window manager issue.

**Comment by alturismo** [comment]
if i turn off the user pass save in the rdp session manager, yes, i see the xrdp login screen ;)

**Comment by alturismo** [comment]
ok, 1 step further on the vm, when i add

allowed_users=anybody

to /etc/X11/Xwrapper.config

i can login, but same like standard installation, no resolution refresh without logout, login

**Comment by RattyDAVE** [comment]
Then it's the window manager.. you may need to put something in .xsession or .Xclients in the user home.

**Comment by alturismo** [comment]
i guess its the mate desktop wich doesnt work nice with sessions and xrandr ...

all good, your docker is running perfectly ;) was just another approach to get a linux vm with dynamic refresh and sound, sound is not so important in my usecase, was be just nice to have ;)

and with your startup addition im perfectly setup now.

**Comment by RattyDAVE** [comment]
you tried the alpha?
